apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    kubernetes.io/dockerconfigjson: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZGFuaWVsZmFyYWciLCJwYXNzd29yZCI6ImdocF9zUG9EYnJXak5YRWZlMVhXZ2MyejN6Q2VaZGQ1VU8yT3RvdE0iLCJlbWFpbCI6ImRhbmllbGZhcmFnMTQ2QGdtYWlsLmNvbSJ9fX0=
