apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include       mime.types; # Include MIME types mapping
        default_type  application/octet-stream; # Default MIME type

        server {
            listen 80;
            server_name localhost;

            root /usr/share/nginx/html;
            index index.html;

            # load file if it exists, fallback to index.html if not
            location / {
                try_files $uri $uri/ /index.html;
            }

            # Serve static files with correct MIME types
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot|json)$ {
                try_files $uri =404;
                access_log off;
                expires max;
                add_header Cache-Control "public, max-age=31536000, immutable";
            }

            # Proxy API requests to the backend
            location /api/ {
                proxy_pass http://backend-service:3000;
                rewrite ^/api(/.*)$ $1 break;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
